---
- name: Deploy Docker Compose application
  hosts: default
  tasks:

    - name: Run Docker Compose Up command
      docker_compose:
        project_src: ./
        state: present
        pull: yes



