---
- name: Deploy Docker Compose application
  hosts: default
  tasks:
    - name: Copy Docker Compose file
      copy:
        src: docker-compose.yml
        dest: "docker-compose.yml"

    - name: Run Docker Compose Up command
      command: /usr/local/bin/docker-compose up -d



