---
- name: Deploy Docker Compose application
  hosts: ec2
  become: yes
  tasks:
    - name: Ensure Docker is installed
      yum:
        name: docker
        state: present

    - name: Ensure Docker is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Ensure Docker Compose is installed
      get_url:
        url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}"
        dest: /usr/local/bin/docker-compose
        mode: '0755'
      vars:
        docker_compose_version: "1.29.2"

    - name: Copy Docker Compose file
      copy:
        src: docker-compose.yml
        dest: /home/ec2-user/docker-compose.yml
        mode: '0644'

    - name: Run Docker Compose
      command: docker-compose up -d
      args:
        chdir: /home/ec2-user
